/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     LED and UART for LaunchPad
  * - <b>Project file</b>:     C:/sensorcontroller/led_art_example/led_toggle_uart_logger.scp
  * - <b>Code prefix</b>:      -
  * - <b>Operating system</b>: TI-RTOS
  * - <b>Tool version</b>:     2.9.0.208
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC2642R1F, package QFN48 7x7 RGZ, revision E (2.1) or F (3.0)
  * - <b>Created</b>:          2026-06-01 15:05:45.188
  * - <b>Computer</b>:         LT5CD3044HTN
  * - <b>User</b>:             a0506076
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * Demonstrates concurrent LED blinking and UART loopback on the CC26X2R1 LaunchPad, driven entirely by
  * the Sensor Controller while the System CPU may remain in deep sleep.
  * 
  * Two tasks run together:
  *  - LED Blinker: toggles the red LED (DIO6) periodically using RTC-based scheduling and the Digital
  * Output Pins resource.
  *  - UART Emulator: provides a bit-banged bidirectional UART on DIO2 (RX) / DIO3 (TX), routed to the
  * LaunchPad's XDS110 Application/User USB serial port. The System CPU application reads received bytes
  * from the SC RX FIFO and writes back to the SC TX FIFO to implement loopback.
  * 
  * See the header in the application source file ("main.c" or similar) for further details and
  * instructions. This file is located in the source code output directory.
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - LED Blinker:
  *     - <b>O: Red LED on LaunchPad</b>: DIO6
  * - UART Emulator:
  *     - <b>UART RX</b>: DIO2
  *     - <b>UART TX</b>: DIO3
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_led_blinker LED Blinker
  * Toggles the red LED (DIO6) on the CC26X2R1 LaunchPad at a fixed rate using RTC-based execution
  * scheduling.
  * 
  * The blink interval is BLINK_INTERVAL RTC ticks (the default RTC tick interval is configured at the
  * project level). With the default 2000/65536 s tick (~30.5 ms), a value of 16 produces approximately a
  * 2 Hz blink rate (~488 ms on, ~488 ms off).
  * 
  * 
  * \subsection section_task_desc_uart_emulator UART Emulator
  * Bidirectional UART emulator on DIO2 (RX) and DIO3 (TX), routed to the LaunchPad's XDS110 USB serial
  * port.
  * 
  * See the description of the UART Emulator resource for details. The System CPU application implements
  * simple loop-back of received data by reading bytes from the SC RX FIFO and writing them back into the
  * SC TX FIFO.
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     LED and UART for LaunchPad
  * - <b>Code prefix</b>:      -
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  * - Hooks for run-time logging
  *
  * @{
  */
#ifndef SCIF_H
#define SCIF_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_tirtos.h"


/// Target chip name
#define SCIF_TARGET_CHIP_NAME_CC2642R1F
/// Target chip package
#define SCIF_TARGET_CHIP_PACKAGE_QFN48_7X7_RGZ

/// Number of tasks implemented by this driver
#define SCIF_TASK_COUNT 2

/// LED Blinker: Task ID
#define SCIF_LED_BLINKER_TASK_ID 0
/// UART Emulator: Task ID
#define SCIF_UART_EMULATOR_TASK_ID 1


/// LED Blinker: LED toggle interval in RTC ticks
#define SCIF_LED_BLINKER_BLINK_INTERVAL 16
/// LED Blinker I/O mapping: Red LED on LaunchPad
#define SCIF_LED_BLINKER_DIO_O_LED 6
/// UART Emulator I/O mapping: UART RX
#define SCIF_UART_EMULATOR_DIO_UART_RX 2
/// UART Emulator I/O mapping: UART TX
#define SCIF_UART_EMULATOR_DIO_UART_TX 3


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// LED Blinker: Task output data structure
typedef struct {
    uint16_t counter; ///< Incremented each time the driver is alerted
} SCIF_LED_BLINKER_OUTPUT_T;


/// LED Blinker: Task state structure
typedef struct {
    uint16_t counter; ///< Incremented once per task execution
} SCIF_LED_BLINKER_STATE_T;


/// UART Emulator: Task configuration structure
typedef struct {
    uint16_t alertMask;            ///< Bit-vector selecting which UART events trigger ALERT interrupt
    uint16_t alertRxFifoThr;       ///< Number of bytes (or higher) in the RX FIFO that triggers ALERT interrupt
    uint16_t alertTxFifoThr;       ///< Number of bytes (or lower) in the TX FIFO that triggers ALERT interrupt
    uint16_t rxByteTimeout;        ///< Maximum number of idle half bit-periods after a received byte before indicating timeout
    uint16_t rxEnableReqIdleCount; ///< Required number of idle half-bits before enabling RX.
} SCIF_UART_EMULATOR_CFG_T;


/// UART Emulator: Task input data structure
typedef struct {
    uint16_t pTxBuffer[64]; ///< TX FIFO ring buffer
} SCIF_UART_EMULATOR_INPUT_T;


/// UART Emulator: Task output data structure
typedef struct {
    uint16_t pRxBuffer[64]; ///< RX FIFO ring buffer
} SCIF_UART_EMULATOR_OUTPUT_T;


/// UART Emulator: Task state structure
typedef struct {
    uint16_t alertBacklog; ///< Bit-vector of events not yet communicated to the application
    uint16_t alertEvents;  ///< Bit-vector of events communicated to the application in the last ALERT interrupt
    uint16_t alertMask;    ///< Currently used ALERT interrupt mask
    uint16_t exit;         ///< Set to exit the UART emulator
    uint16_t rxEnable;     ///< Set to enable RX, or clear to disable RX (controls whether start bits are detected)
    uint16_t rxEnabled;    ///< Is RX currently enabled?
    uint16_t rxHead;       ///< RX FIFO head index (updated by the Sensor Controller)
    uint16_t rxTail;       ///< RX FIFO tail index (updated by the application)
    uint16_t txHead;       ///< TX FIFO head index (updated by the application)
    uint16_t txTail;       ///< TX FIFO tail index (updated by the Sensor Controller)
} SCIF_UART_EMULATOR_STATE_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_LED_BLINKER_OUTPUT_T output;
        SCIF_LED_BLINKER_STATE_T state;
    } ledBlinker;
    struct {
        SCIF_UART_EMULATOR_CFG_T cfg;
        SCIF_UART_EMULATOR_INPUT_T input;
        SCIF_UART_EMULATOR_OUTPUT_T output;
        SCIF_UART_EMULATOR_STATE_T state;
    } uartEmulator;
} SCIF_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifTaskData    (*((volatile SCIF_TASK_DATA_T*) 0x400E0164))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifDriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifReinitTaskIo(uint32_t bvTaskIds);


// RTC-based tick generation control
void scifStartRtcTicks(uint32_t tickStart, uint32_t tickPeriod);
void scifStartRtcTicksNow(uint32_t tickPeriod);
void scifStopRtcTicks(void);

/// Maximum number of characters that can be stored in the UART TX FIFO
#define SCIF_UART_TX_FIFO_MAX_COUNT                  63
/// Maximum number of characters that can be stored in the UART RX FIFO
#define SCIF_UART_RX_FIFO_MAX_COUNT                  63

/// RX character flag: RX timeout occurred after receiving this character
#define BV_SCIF_UART_RX_TIMEOUT                      0x0800
/// RX character flag: RX FIFO ran full when receiving this character (this character may be invalid)
#define BV_SCIF_UART_RX_OVERFLOW                     0x0400
/// RX character flag: Break occurred when receiving this character
#define BV_SCIF_UART_RX_BREAK                        0x0200
/// RX character flag: Framing error occurred when receiving this character
#define BV_SCIF_UART_RX_FRAMING_ERROR                0x0100

/// UART ALERT event: RX FIFO at or above the specified threshold
#define BV_SCIF_UART_ALERT_RX_FIFO_ABOVE_THR         0x0001
/// UART ALERT event: RX byte timeout occurred
#define BV_SCIF_UART_ALERT_RX_BYTE_TIMEOUT           0x0002
/// UART ALERT event: Break or framing error occurred
#define BV_SCIF_UART_ALERT_RX_BREAK_OR_FRAMING_ERROR 0x0004
/// UART ALERT event: TX FIFO at or below the specified threshold
#define BV_SCIF_UART_ALERT_TX_FIFO_BELOW_THR         0x0008


// UART control functions
void scifUartSetRxTimeout(uint16_t rxTimeout);
void scifUartSetRxEnableReqIdleCount(uint16_t rxEnableReqIdleCount);
void scifUartRxEnable(uint16_t rxEnable);
void scifUartStopEmulator(void);
void scifUartSetBaudRate(uint32_t baudRate);

// UART RX FIFO access functions
void scifUartSetRxFifoThr(uint16_t threshold);
uint32_t scifUartGetRxFifoCount(void);
uint16_t scifUartRxGetChar(void);
void scifUartRxGetChars(char* pBuffer, uint32_t count);
void scifUartRxGetCharsWithFlags(uint16_t* pBuffer, uint32_t count);

// UART TX FIFO access functions
void scifUartSetTxFifoThr(uint16_t threshold);
uint32_t scifUartGetTxFifoCount(void);
void scifUartTxPutChar(char c);
void scifUartTxPutCharDelayed(char c, uint8_t delay);
void scifUartTxPutChars(char* pBuffer, uint32_t count);

// UART event/interrupt functions
uint16_t scifUartGetEvents(void);
void scifUartClearEvents(void);
void scifUartSetEventMask(uint16_t mask);


#endif
//@}


// Generated by LT5CD3044HTN at 2026-06-01 15:05:45.188
